version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto/config:/mosquitto/config

  influxdb:
    image: influxdb:2.6
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecuretoken
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  mission-time:
    build: ./mission_time
    container_name: spacesim-mission-time
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MISSION_FILE=/app/mission.yaml
    volumes:
      - ../missions/${MISSION}.yaml:/app/mission.yaml:ro

  satellite:
    build: ../modules/satellite
    container_name: spacesim-satellite-1
    depends_on:
      - mosquitto
      - influxdb
      - mission-time
    environment:
      - SAT_ID=1
      - MQTT_BROKER=mosquitto
      - MISSION_FILE=/app/mission.yaml
    volumes:
      - ../missions/${MISSION}.yaml:/app/mission.yaml:ro

  satellite-2:
    build: ../modules/satellite
    container_name: spacesim-satellite-2
    depends_on:
      - mosquitto
      - influxdb
      - mission-time
    environment:
      - SAT_ID=2
      - MQTT_BROKER=mosquitto
      - MISSION_FILE=/app/mission.yaml
    volumes:
      - ../missions/${MISSION}.yaml:/app/mission.yaml:ro

  groundstation:
    build: ../modules/groundstation
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=org
      - INFLUX_BUCKET=telemetry
      - INFLUX_TOKEN=supersecuretoken

volumes:
  influxdb-data:
  grafana-data:
