apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      organization: org
      defaultBucket: telemetry
      version: Flux
    secureJsonData:
      token: supersecuretoken
